import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";

import { NavBar } from "@/components/NavBar";
import Logo from "@/components/Logo";
import Footer from "@/components/Footer";
import AuthButton from "@/components/AuthButton";

import { ApolloWrapper } from "@/providers/ApolloWrapper";
import { SessionWrapper } from "@/providers/SessionWrapper";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <div className="mx-auto w-full max-w-5xl px-4">
            <div className="flex flex-row justify-between items-center">
              <Link href="/">
                <Logo />
              </Link>
              <NavBar />
              <AuthButton />
            </div>
          </div>
          <ApolloWrapper>{children}</ApolloWrapper>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
