"User represents an individual who can create and manage persons in the family tree."
type User {
  id: ID!
  email: String!
  createdAt: String!
}

"Person represents an individual in a family tree."
type Person {
  id: ID!
  firstName: String
  lastName: String
  gender: Gender
  birthDate: String
  deathDate: String
  birthLocation: Location
  deathLocation: Location
  notes: String
  createdBy: ID
  createdAt: String
  parents: [ID!]
  children: [ID!]
  spouses: [ID!]
}

type Relationship {
  id: ID!
  person: ID!
  relatedPerson: ID!
  type: RelationshipType!
}

type FamilyTree {
  id: ID!
  name: String!
  description: String
  createdBy: ID!
  createdAt: String
  members: [FamilyTreeMember]
}

type FamilyTreeMember {
  id: String
  data: FamilyTreeMemberData
  rels: FamilyTreeRelationships
}

type FamilyTreeMemberData {
  gender: String
  firstName: String
  lastName: String
  birthday: String
  death: String
  notes: String
}

type FamilyTreeRelationships {
  parents: [String]
  spouses: [String]
  children: [String]
}

type Location {
  id: ID!
  name: String!
  latitude: Float
  longitude: Float
}

enum Gender {
  MALE
  FEMALE
}

enum RelationshipType {
  PARENT
  CHILD
  SPOUSE
}

type Query {
  persons: [Person!]!
  person(id: ID!): Person
  relationships(personId: ID!): [Relationship!]!
  familyTreesByUser(id: ID!): [FamilyTree!]!
}

type Mutation {
  createPerson(input: CreatePersonInput!): Person!
  createRelationship(input: CreateRelationshipInput!): Relationship!
}

input CreatePersonInput {
  firstName: String
  lastName: String
  gender: String
  birthDate: String
  deathDate: String
  birthLocationId: ID
  deathLocationId: ID
  notes: String
  createdBy: ID
}

input CreateRelationshipInput {
  personId: ID!
  relatedPersonId: ID!
  type: RelationshipType!
  notes: String
}
